// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: protos/metadata/req_res.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateObjRequest_ObjIndex_IndexType int32

const (
	CreateObjRequest_ObjIndex_UNSET_NOTALLOW CreateObjRequest_ObjIndex_IndexType = 0 // 占位, 不允许使用
	CreateObjRequest_ObjIndex_COMMON         CreateObjRequest_ObjIndex_IndexType = 1
	CreateObjRequest_ObjIndex_UNIQUE         CreateObjRequest_ObjIndex_IndexType = 2
)

// Enum value maps for CreateObjRequest_ObjIndex_IndexType.
var (
	CreateObjRequest_ObjIndex_IndexType_name = map[int32]string{
		0: "UNSET_NOTALLOW",
		1: "COMMON",
		2: "UNIQUE",
	}
	CreateObjRequest_ObjIndex_IndexType_value = map[string]int32{
		"UNSET_NOTALLOW": 0,
		"COMMON":         1,
		"UNIQUE":         2,
	}
)

func (x CreateObjRequest_ObjIndex_IndexType) Enum() *CreateObjRequest_ObjIndex_IndexType {
	p := new(CreateObjRequest_ObjIndex_IndexType)
	*p = x
	return p
}

func (x CreateObjRequest_ObjIndex_IndexType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateObjRequest_ObjIndex_IndexType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_metadata_req_res_proto_enumTypes[0].Descriptor()
}

func (CreateObjRequest_ObjIndex_IndexType) Type() protoreflect.EnumType {
	return &file_protos_metadata_req_res_proto_enumTypes[0]
}

func (x CreateObjRequest_ObjIndex_IndexType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateObjRequest_ObjIndex_IndexType.Descriptor instead.
func (CreateObjRequest_ObjIndex_IndexType) EnumDescriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{0, 0, 0}
}

type CreateObjRequest_ObjField_FieldType int32

const (
	CreateObjRequest_ObjField_UNSET_NOTALLOW CreateObjRequest_ObjField_FieldType = 0 // 占位, 不允许使用
	CreateObjRequest_ObjField_ID             CreateObjRequest_ObjField_FieldType = 1 // 本对象的id, 无符号自增int
	CreateObjRequest_ObjField_LOOKUPID       CreateObjRequest_ObjField_FieldType = 2 // 其他对象的id, 无符号int
	CreateObjRequest_ObjField_INTEGER        CreateObjRequest_ObjField_FieldType = 3 // int
	CreateObjRequest_ObjField_DOUBLE         CreateObjRequest_ObjField_FieldType = 4 // double
	CreateObjRequest_ObjField_STRING         CreateObjRequest_ObjField_FieldType = 5 // varchar(255)
	CreateObjRequest_ObjField_TEXT           CreateObjRequest_ObjField_FieldType = 6 // text
	CreateObjRequest_ObjField_DATETIME       CreateObjRequest_ObjField_FieldType = 7 // datetime
)

// Enum value maps for CreateObjRequest_ObjField_FieldType.
var (
	CreateObjRequest_ObjField_FieldType_name = map[int32]string{
		0: "UNSET_NOTALLOW",
		1: "ID",
		2: "LOOKUPID",
		3: "INTEGER",
		4: "DOUBLE",
		5: "STRING",
		6: "TEXT",
		7: "DATETIME",
	}
	CreateObjRequest_ObjField_FieldType_value = map[string]int32{
		"UNSET_NOTALLOW": 0,
		"ID":             1,
		"LOOKUPID":       2,
		"INTEGER":        3,
		"DOUBLE":         4,
		"STRING":         5,
		"TEXT":           6,
		"DATETIME":       7,
	}
)

func (x CreateObjRequest_ObjField_FieldType) Enum() *CreateObjRequest_ObjField_FieldType {
	p := new(CreateObjRequest_ObjField_FieldType)
	*p = x
	return p
}

func (x CreateObjRequest_ObjField_FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateObjRequest_ObjField_FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_metadata_req_res_proto_enumTypes[1].Descriptor()
}

func (CreateObjRequest_ObjField_FieldType) Type() protoreflect.EnumType {
	return &file_protos_metadata_req_res_proto_enumTypes[1]
}

func (x CreateObjRequest_ObjField_FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateObjRequest_ObjField_FieldType.Descriptor instead.
func (CreateObjRequest_ObjField_FieldType) EnumDescriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{0, 1, 0}
}

type CreateObjRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string                       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Fields      []*CreateObjRequest_ObjField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	ObjIndex    []*CreateObjRequest_ObjIndex `protobuf:"bytes,4,rep,name=obj_index,json=objIndex,proto3" json:"obj_index,omitempty"`
}

func (x *CreateObjRequest) Reset() {
	*x = CreateObjRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjRequest) ProtoMessage() {}

func (x *CreateObjRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjRequest.ProtoReflect.Descriptor instead.
func (*CreateObjRequest) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{0}
}

func (x *CreateObjRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateObjRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateObjRequest) GetFields() []*CreateObjRequest_ObjField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateObjRequest) GetObjIndex() []*CreateObjRequest_ObjIndex {
	if x != nil {
		return x.ObjIndex
	}
	return nil
}

type CreateObjReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateObjReply) Reset() {
	*x = CreateObjReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjReply) ProtoMessage() {}

func (x *CreateObjReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjReply.ProtoReflect.Descriptor instead.
func (*CreateObjReply) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{1}
}

type CreateObjRequest_ObjIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ObjFieldNames []string                            `protobuf:"bytes,1,rep,name=obj_field_names,json=objFieldNames,proto3" json:"obj_field_names,omitempty"`
	IndexType     CreateObjRequest_ObjIndex_IndexType `protobuf:"varint,2,opt,name=index_type,json=indexType,proto3,enum=metadata.CreateObjRequest_ObjIndex_IndexType" json:"index_type,omitempty"`
}

func (x *CreateObjRequest_ObjIndex) Reset() {
	*x = CreateObjRequest_ObjIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjRequest_ObjIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjRequest_ObjIndex) ProtoMessage() {}

func (x *CreateObjRequest_ObjIndex) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjRequest_ObjIndex.ProtoReflect.Descriptor instead.
func (*CreateObjRequest_ObjIndex) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateObjRequest_ObjIndex) GetObjFieldNames() []string {
	if x != nil {
		return x.ObjFieldNames
	}
	return nil
}

func (x *CreateObjRequest_ObjIndex) GetIndexType() CreateObjRequest_ObjIndex_IndexType {
	if x != nil {
		return x.IndexType
	}
	return CreateObjRequest_ObjIndex_UNSET_NOTALLOW
}

type CreateObjRequest_ObjField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FieldType   CreateObjRequest_ObjField_FieldType `protobuf:"varint,2,opt,name=field_type,json=fieldType,proto3,enum=metadata.CreateObjRequest_ObjField_FieldType" json:"field_type,omitempty"`
	LookupObjId int32                               `protobuf:"varint,3,opt,name=lookup_obj_id,json=lookupObjId,proto3" json:"lookup_obj_id,omitempty"`
	Description string                              `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IsAllowNull bool                                `protobuf:"varint,5,opt,name=is_allow_null,json=isAllowNull,proto3" json:"is_allow_null,omitempty"`
}

func (x *CreateObjRequest_ObjField) Reset() {
	*x = CreateObjRequest_ObjField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjRequest_ObjField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjRequest_ObjField) ProtoMessage() {}

func (x *CreateObjRequest_ObjField) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjRequest_ObjField.ProtoReflect.Descriptor instead.
func (*CreateObjRequest_ObjField) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CreateObjRequest_ObjField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateObjRequest_ObjField) GetFieldType() CreateObjRequest_ObjField_FieldType {
	if x != nil {
		return x.FieldType
	}
	return CreateObjRequest_ObjField_UNSET_NOTALLOW
}

func (x *CreateObjRequest_ObjField) GetLookupObjId() int32 {
	if x != nil {
		return x.LookupObjId
	}
	return 0
}

func (x *CreateObjRequest_ObjField) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateObjRequest_ObjField) GetIsAllowNull() bool {
	if x != nil {
		return x.IsAllowNull
	}
	return false
}

var File_protos_metadata_req_res_proto protoreflect.FileDescriptor

var file_protos_metadata_req_res_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x72, 0x65, 0x71, 0x5f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0xd0, 0x05, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x4f, 0x62, 0x6a, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x73, 0x12, 0x40, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x4f, 0x62, 0x6a, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x1a, 0xb9, 0x01, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x26, 0x0a, 0x0f, 0x6f, 0x62, 0x6a, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x62, 0x6a, 0x46, 0x69,
	0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x4c, 0x0a, 0x0a, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62,
	0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x62, 0x6a, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x2e, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x54, 0x79, 0x70, 0x65, 0x22, 0x37, 0x0a, 0x09, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x5f, 0x4e, 0x4f, 0x54,
	0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d, 0x4f,
	0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x49, 0x51, 0x55, 0x45, 0x10, 0x02, 0x1a,
	0xca, 0x02, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x4c, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x4f, 0x62, 0x6a, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x09, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22,
	0x0a, 0x0d, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x5f, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x4f, 0x62, 0x6a,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41,
	0x6c, 0x6c, 0x6f, 0x77, 0x4e, 0x75, 0x6c, 0x6c, 0x22, 0x72, 0x0a, 0x09, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x5f, 0x4e,
	0x4f, 0x54, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10,
	0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x4f, 0x4f, 0x4b, 0x55, 0x50, 0x49, 0x44, 0x10, 0x02, 0x12,
	0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x54, 0x45, 0x47, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49,
	0x4e, 0x47, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x45, 0x58, 0x54, 0x10, 0x06, 0x12, 0x0c,
	0x0a, 0x08, 0x44, 0x41, 0x54, 0x45, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x07, 0x22, 0x10, 0x0a, 0x0e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x6f, 0x73,
	0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x6d, 0x73, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_metadata_req_res_proto_rawDescOnce sync.Once
	file_protos_metadata_req_res_proto_rawDescData = file_protos_metadata_req_res_proto_rawDesc
)

func file_protos_metadata_req_res_proto_rawDescGZIP() []byte {
	file_protos_metadata_req_res_proto_rawDescOnce.Do(func() {
		file_protos_metadata_req_res_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_metadata_req_res_proto_rawDescData)
	})
	return file_protos_metadata_req_res_proto_rawDescData
}

var file_protos_metadata_req_res_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protos_metadata_req_res_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_metadata_req_res_proto_goTypes = []interface{}{
	(CreateObjRequest_ObjIndex_IndexType)(0), // 0: metadata.CreateObjRequest.ObjIndex.IndexType
	(CreateObjRequest_ObjField_FieldType)(0), // 1: metadata.CreateObjRequest.ObjField.FieldType
	(*CreateObjRequest)(nil),                 // 2: metadata.CreateObjRequest
	(*CreateObjReply)(nil),                   // 3: metadata.CreateObjReply
	(*CreateObjRequest_ObjIndex)(nil),        // 4: metadata.CreateObjRequest.ObjIndex
	(*CreateObjRequest_ObjField)(nil),        // 5: metadata.CreateObjRequest.ObjField
}
var file_protos_metadata_req_res_proto_depIdxs = []int32{
	5, // 0: metadata.CreateObjRequest.fields:type_name -> metadata.CreateObjRequest.ObjField
	4, // 1: metadata.CreateObjRequest.obj_index:type_name -> metadata.CreateObjRequest.ObjIndex
	0, // 2: metadata.CreateObjRequest.ObjIndex.index_type:type_name -> metadata.CreateObjRequest.ObjIndex.IndexType
	1, // 3: metadata.CreateObjRequest.ObjField.field_type:type_name -> metadata.CreateObjRequest.ObjField.FieldType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protos_metadata_req_res_proto_init() }
func file_protos_metadata_req_res_proto_init() {
	if File_protos_metadata_req_res_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_metadata_req_res_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metadata_req_res_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metadata_req_res_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjRequest_ObjIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metadata_req_res_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjRequest_ObjField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_metadata_req_res_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_metadata_req_res_proto_goTypes,
		DependencyIndexes: file_protos_metadata_req_res_proto_depIdxs,
		EnumInfos:         file_protos_metadata_req_res_proto_enumTypes,
		MessageInfos:      file_protos_metadata_req_res_proto_msgTypes,
	}.Build()
	File_protos_metadata_req_res_proto = out.File
	file_protos_metadata_req_res_proto_rawDesc = nil
	file_protos_metadata_req_res_proto_goTypes = nil
	file_protos_metadata_req_res_proto_depIdxs = nil
}
