// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.10
// source: protos/metadata/req_res.proto

package metadata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateObjRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description *string     `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Fields      []*ObjField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	ObjIndex    []*ObjIndex `protobuf:"bytes,4,rep,name=obj_index,json=objIndex,proto3" json:"obj_index,omitempty"`
}

func (x *CreateObjRequest) Reset() {
	*x = CreateObjRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjRequest) ProtoMessage() {}

func (x *CreateObjRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjRequest.ProtoReflect.Descriptor instead.
func (*CreateObjRequest) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{0}
}

func (x *CreateObjRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateObjRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateObjRequest) GetFields() []*ObjField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateObjRequest) GetObjIndex() []*ObjIndex {
	if x != nil {
		return x.ObjIndex
	}
	return nil
}

type CreateObjReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateObjReply) Reset() {
	*x = CreateObjReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateObjReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateObjReply) ProtoMessage() {}

func (x *CreateObjReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateObjReply.ProtoReflect.Descriptor instead.
func (*CreateObjReply) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{1}
}

type GetObjFieldsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetObjFieldsRequest) Reset() {
	*x = GetObjFieldsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjFieldsRequest) ProtoMessage() {}

func (x *GetObjFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjFieldsRequest.ProtoReflect.Descriptor instead.
func (*GetObjFieldsRequest) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjFieldsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetObjFieldsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetObjFieldsReply) Reset() {
	*x = GetObjFieldsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_metadata_req_res_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetObjFieldsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjFieldsReply) ProtoMessage() {}

func (x *GetObjFieldsReply) ProtoReflect() protoreflect.Message {
	mi := &file_protos_metadata_req_res_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjFieldsReply.ProtoReflect.Descriptor instead.
func (*GetObjFieldsReply) Descriptor() ([]byte, []int) {
	return file_protos_metadata_req_res_proto_rawDescGZIP(), []int{3}
}

var File_protos_metadata_req_res_proto protoreflect.FileDescriptor

var file_protos_metadata_req_res_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x72, 0x65, 0x71, 0x5f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x4f, 0x62, 0x6a, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x4f, 0x62, 0x6a, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x62, 0x6a,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x29, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x62, 0x6a, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x59, 0x6f, 0x73, 0x6f, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x6d, 0x73,
	0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protos_metadata_req_res_proto_rawDescOnce sync.Once
	file_protos_metadata_req_res_proto_rawDescData = file_protos_metadata_req_res_proto_rawDesc
)

func file_protos_metadata_req_res_proto_rawDescGZIP() []byte {
	file_protos_metadata_req_res_proto_rawDescOnce.Do(func() {
		file_protos_metadata_req_res_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_metadata_req_res_proto_rawDescData)
	})
	return file_protos_metadata_req_res_proto_rawDescData
}

var file_protos_metadata_req_res_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_metadata_req_res_proto_goTypes = []interface{}{
	(*CreateObjRequest)(nil),    // 0: metadata.CreateObjRequest
	(*CreateObjReply)(nil),      // 1: metadata.CreateObjReply
	(*GetObjFieldsRequest)(nil), // 2: metadata.GetObjFieldsRequest
	(*GetObjFieldsReply)(nil),   // 3: metadata.GetObjFieldsReply
	(*ObjField)(nil),            // 4: metadata.ObjField
	(*ObjIndex)(nil),            // 5: metadata.ObjIndex
}
var file_protos_metadata_req_res_proto_depIdxs = []int32{
	4, // 0: metadata.CreateObjRequest.fields:type_name -> metadata.ObjField
	5, // 1: metadata.CreateObjRequest.obj_index:type_name -> metadata.ObjIndex
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_metadata_req_res_proto_init() }
func file_protos_metadata_req_res_proto_init() {
	if File_protos_metadata_req_res_proto != nil {
		return
	}
	file_protos_metadata_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_metadata_req_res_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metadata_req_res_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateObjReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metadata_req_res_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjFieldsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_metadata_req_res_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetObjFieldsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_metadata_req_res_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_metadata_req_res_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_metadata_req_res_proto_goTypes,
		DependencyIndexes: file_protos_metadata_req_res_proto_depIdxs,
		MessageInfos:      file_protos_metadata_req_res_proto_msgTypes,
	}.Build()
	File_protos_metadata_req_res_proto = out.File
	file_protos_metadata_req_res_proto_rawDesc = nil
	file_protos_metadata_req_res_proto_goTypes = nil
	file_protos_metadata_req_res_proto_depIdxs = nil
}
