// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: protos/metadata/service.proto

package metadata

import (
	context "context"
	common "github.com/Yosorable/ms-shared/protoc_gen/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MetadataClient is the client API for Metadata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetadataClient interface {
	DynamicCall(ctx context.Context, in *common.DynamicCallRequest, opts ...grpc.CallOption) (*common.DynamicCallReply, error)
	CreateObj(ctx context.Context, in *CreateObjRequest, opts ...grpc.CallOption) (*CreateObjReply, error)
	GetObjFields(ctx context.Context, in *GetObjFieldsRequest, opts ...grpc.CallOption) (*GetObjFieldsReply, error)
}

type metadataClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataClient(cc grpc.ClientConnInterface) MetadataClient {
	return &metadataClient{cc}
}

func (c *metadataClient) DynamicCall(ctx context.Context, in *common.DynamicCallRequest, opts ...grpc.CallOption) (*common.DynamicCallReply, error) {
	out := new(common.DynamicCallReply)
	err := c.cc.Invoke(ctx, "/metadata.Metadata/DynamicCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataClient) CreateObj(ctx context.Context, in *CreateObjRequest, opts ...grpc.CallOption) (*CreateObjReply, error) {
	out := new(CreateObjReply)
	err := c.cc.Invoke(ctx, "/metadata.Metadata/CreateObj", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataClient) GetObjFields(ctx context.Context, in *GetObjFieldsRequest, opts ...grpc.CallOption) (*GetObjFieldsReply, error) {
	out := new(GetObjFieldsReply)
	err := c.cc.Invoke(ctx, "/metadata.Metadata/GetObjFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServer is the server API for Metadata service.
// All implementations must embed UnimplementedMetadataServer
// for forward compatibility
type MetadataServer interface {
	DynamicCall(context.Context, *common.DynamicCallRequest) (*common.DynamicCallReply, error)
	CreateObj(context.Context, *CreateObjRequest) (*CreateObjReply, error)
	GetObjFields(context.Context, *GetObjFieldsRequest) (*GetObjFieldsReply, error)
	mustEmbedUnimplementedMetadataServer()
}

// UnimplementedMetadataServer must be embedded to have forward compatible implementations.
type UnimplementedMetadataServer struct {
}

func (UnimplementedMetadataServer) DynamicCall(context.Context, *common.DynamicCallRequest) (*common.DynamicCallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DynamicCall not implemented")
}
func (UnimplementedMetadataServer) CreateObj(context.Context, *CreateObjRequest) (*CreateObjReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObj not implemented")
}
func (UnimplementedMetadataServer) GetObjFields(context.Context, *GetObjFieldsRequest) (*GetObjFieldsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObjFields not implemented")
}
func (UnimplementedMetadataServer) mustEmbedUnimplementedMetadataServer() {}

// UnsafeMetadataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServer will
// result in compilation errors.
type UnsafeMetadataServer interface {
	mustEmbedUnimplementedMetadataServer()
}

func RegisterMetadataServer(s grpc.ServiceRegistrar, srv MetadataServer) {
	s.RegisterService(&Metadata_ServiceDesc, srv)
}

func _Metadata_DynamicCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.DynamicCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServer).DynamicCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.Metadata/DynamicCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServer).DynamicCall(ctx, req.(*common.DynamicCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metadata_CreateObj_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServer).CreateObj(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.Metadata/CreateObj",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServer).CreateObj(ctx, req.(*CreateObjRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Metadata_GetObjFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServer).GetObjFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/metadata.Metadata/GetObjFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServer).GetObjFields(ctx, req.(*GetObjFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Metadata_ServiceDesc is the grpc.ServiceDesc for Metadata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Metadata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metadata.Metadata",
	HandlerType: (*MetadataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DynamicCall",
			Handler:    _Metadata_DynamicCall_Handler,
		},
		{
			MethodName: "CreateObj",
			Handler:    _Metadata_CreateObj_Handler,
		},
		{
			MethodName: "GetObjFields",
			Handler:    _Metadata_GetObjFields_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/metadata/service.proto",
}
